"""session schema

Revision ID: 7cf099bea84b
Revises: 0001
Create Date: 2026-06-04 01:31:56.178590

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7cf099bea84b"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connector",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("spec", sa.JSON(), nullable=True),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tests", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "marketprofile",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("default_connectors", sa.JSON(), nullable=False),
        sa.Column("default_featurizer_config", sa.JSON(), nullable=False),
        sa.Column("regime_labels", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "session",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("market_profile", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timeframe_start", sa.Date(), nullable=False),
        sa.Column("timeframe_end", sa.Date(), nullable=False),
        sa.Column("stage", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("auto", sa.Boolean(), nullable=False),
        sa.Column("featurizer_config", sa.JSON(), nullable=False),
        sa.Column("pending_sources", sa.JSON(), nullable=False),
        sa.Column("conversation", sa.JSON(), nullable=False),
        sa.Column("activity_events", sa.JSON(), nullable=False),
        sa.Column("stage_history", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dataartifact",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("round", sa.Integer(), nullable=False),
        sa.Column("sources", sa.JSON(), nullable=False),
        sa.Column("data_manifest", sa.JSON(), nullable=False),
        sa.Column("raw_data", sa.JSON(), nullable=True),
        sa.Column("raw_data_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cached_from_session_id", sa.Uuid(), nullable=True),
        sa.Column("cached_from_artifact_id", sa.Uuid(), nullable=True),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "featureartifact",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("data_artifact_id", sa.Uuid(), nullable=False),
        sa.Column("featurizer_config_snapshot", sa.JSON(), nullable=False),
        sa.Column("feature_manifest", sa.JSON(), nullable=False),
        sa.Column("feature_matrix_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("matrix_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("config_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cached_from_session_id", sa.Uuid(), nullable=True),
        sa.Column("cached_from_artifact_id", sa.Uuid(), nullable=True),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["data_artifact_id"],
            ["dataartifact.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "analysisresult",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("feature_artifact_id", sa.Uuid(), nullable=False),
        sa.Column("regime", sa.JSON(), nullable=True),
        sa.Column("direction", sa.JSON(), nullable=True),
        sa.Column("feature_importance", sa.JSON(), nullable=True),
        sa.Column("drift", sa.JSON(), nullable=True),
        sa.Column("backtest", sa.JSON(), nullable=True),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("feature_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cached_from_session_id", sa.Uuid(), nullable=True),
        sa.Column("cached_from_artifact_id", sa.Uuid(), nullable=True),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["feature_artifact_id"],
            ["featureartifact.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("run")
    op.create_index("idx_session_created_at", "session", ["created_at"])
    op.create_index("idx_data_artifact_session_id", "dataartifact", ["session_id"])
    op.create_index("idx_data_artifact_source_hash", "dataartifact", ["source_hash"])
    op.create_index("idx_feature_artifact_session_id", "featureartifact", ["session_id"])
    op.create_index("idx_feature_artifact_config_hash", "featureartifact", ["config_hash"])
    op.create_index("idx_analysis_result_session_id", "analysisresult", ["session_id"])
    op.create_index("idx_analysis_result_feature_hash", "analysisresult", ["feature_hash"])
    op.create_index("idx_connector_is_active", "connector", ["is_active"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "run",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("completed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("date_range_start", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("date_range_end", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "tasks", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False
        ),
        sa.Column(
            "result", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("error", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("run_pkey")),
    )
    op.drop_index("idx_connector_is_active", table_name="connector")
    op.drop_index("idx_analysis_result_feature_hash", table_name="analysisresult")
    op.drop_index("idx_analysis_result_session_id", table_name="analysisresult")
    op.drop_index("idx_feature_artifact_config_hash", table_name="featureartifact")
    op.drop_index("idx_feature_artifact_session_id", table_name="featureartifact")
    op.drop_index("idx_data_artifact_source_hash", table_name="dataartifact")
    op.drop_index("idx_data_artifact_session_id", table_name="dataartifact")
    op.drop_index("idx_session_created_at", table_name="session")
    op.drop_table("analysisresult")
    op.drop_table("featureartifact")
    op.drop_table("dataartifact")
    op.drop_table("session")
    op.drop_table("marketprofile")
    op.drop_table("connector")
    # ### end Alembic commands ###
